{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from PIL import Image\n",
    "import src.pic_process as pic_pro\n",
    "\n",
    "#test_align\n",
    "base_image = Image.open(r\"calibration\\data\\20241121_reference\\1_06_05_E1_0130\\1_06_05_E1_0130.tif\")\n",
    "reference_image = Image.open(r\"calibration/data/20241121_reference/1_06_05_E1_0130/1_06_05_E1_0433.tif\")\n",
    "\n",
    "# 假设的距离值\n",
    "base_image_distance = 101.69\n",
    "reference_image_distance = 92.1\n",
    "\n",
    "# 垂直对齐\n",
    "#processed_base_image_v, processed_reference_image_v = align_images(base_image, base_image_distance, reference_image, reference_image_distance, is_vertical=True)\n",
    "\n",
    "# 水平对齐\n",
    "processed_base_image_h, processed_reference_image_h = pic_pro.align_images(base_image, base_image_distance, reference_image, reference_image_distance, is_vertical=True)\n",
    "\n",
    "\n",
    "processed_base_image_h.save(\"processed_base_image_h.tif\")\n",
    "processed_reference_image_h.save(\"processed_reference_image_h.tif\")\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Resized image successfully.\n",
      "Resized image successfully.\n"
     ]
    }
   ],
   "source": [
    "from PIL import Image\n",
    "import src.pic_process as pic_pro\n",
    "from pathlib import Path\n",
    "import numpy as np\n",
    "# output_path = Path(f\"{image_path.parent}/resized_{image_path.stem}{image_path.suffix}\")\n",
    "\n",
    "\n",
    "aligned_data_path=Path(r\"C:\\Users\\huang\\work\\dataset\\calibration\\data\\merged_reference_data.csv\")\n",
    "\n",
    "base_image_folder = Path(r\"C:\\Users\\huang\\work\\dataset\\calibration\\data\\20241209\\anomaly\")\n",
    "mask_image_folder=Path(r\"C:\\Users\\huang\\work\\bevel-ml\\trunk\\data\\output\\20241118\\rd4ad_resnet18_512_cc_70epoch\\version_0\\anomaly_regions_hist_abstract\\0.08\")\n",
    "back_image_folder=Path(r\"C:\\Users\\huang\\work\\dataset\\calibration\\data\\20241209\\normal\")\n",
    "##########################################################################################################\n",
    "\n",
    "base_image_path = base_image_folder / \"1_12_01_A1_0150_O.tif\"\n",
    "mask_image_path=mask_image_folder/\"1_12_01_A1_0150_O.png\" #png todo functionaize\n",
    "back_image_path=back_image_folder/\"2_02_01_A1_0094_O.tif\" \n",
    "scale_factor=3\n",
    "\n",
    "#########################################################################################################\n",
    "output_root = Path(r\"C:\\Users\\huang\\work\\dataset\\calibration\\data\\20241209\\output\")\n",
    "output_folder = output_root / base_image_path.stem\n",
    "output_filename = str(back_image_path.stem) + f\"_s{scale_factor}\" + \".png\"\n",
    "\n",
    "base_image = Image.open(base_image_path)\n",
    "base_image = pic_pro.resize_image(base_image,(512,512))\n",
    "base_array=np.array(base_image,dtype=np.int16)\n",
    "base_image_name=base_image_path.stem\n",
    "base_image_dis=pic_pro.get_distance(base_image_name,aligned_data_path)\n",
    "               \n",
    "mask_image = Image.open(mask_image_path)\n",
    "mask_array=np.array(mask_image,dtype=np.int16)\n",
    "mask_image_name=mask_image_path.stem\n",
    "\n",
    "back_image = Image.open(back_image_path)\n",
    "back_image = pic_pro.resize_image(back_image,(512,512))\n",
    "back_array=np.array(back_image,dtype=np.int16)\n",
    "back_image_name=back_image_path.stem\n",
    "back_image_dis=pic_pro.get_distance(back_image_name,aligned_data_path)\n",
    "\n",
    "reference_image_mean_array,reference_image_mode_array=pic_pro.generate_reference_images(base_image,mask_image,mask_image_name)\n",
    "\n",
    "diff_image_mean_array = pic_pro.calculate_image_difference(base_array, reference_image_mean_array)\n",
    "#diff_image_mode_array = pic_pro.calculate_image_difference(base_array, reference_image_mode_array)\n",
    "\n",
    "masked_diff_image_mean_array=pic_pro.apply_mask_to_image(diff_image_mean_array,mask_array)\n",
    "#masked_diff_image_mode_array=pic_pro.apply_mask_to_image(diff_image_mode_array,mask_array)\n",
    "\n",
    "aligned_base_image, aligned_reference_image_mean=pic_pro.align_images(back_array,back_image_dis,masked_diff_image_mean_array,base_image_dis,True,False)\n",
    "#aligned_base_image, aligned_reference_image_mode=pic_pro.align_images(back_array,back_image_dis,masked_diff_image_mode_array,base_image_dis,True,False)\n",
    "\n",
    "aligned_reference_image_mean = pic_pro.scale_image(aligned_reference_image_mean, scale_factor)\n",
    "#mode\n",
    "\n",
    "result_image_mean = pic_pro.apply_difference_to_image(aligned_base_image, aligned_reference_image_mean)\n",
    "#result_image_mode = pic_pro.apply_difference_to_image(aligned_base_image, aligned_reference_image_mode)\n",
    "result_image_mean=pic_pro.from_int16_to_uint8(result_image_mean)\n",
    "#result_image_mode=pic_pro.from_int16_to_uint8(result_image_mode)\n",
    "\n",
    "if not output_folder.exists():\n",
    "    output_folder.mkdir(parents=True,exist_ok=True)\n",
    "Image.fromarray(result_image_mean).save(output_folder / output_filename)\n",
    "base_image.save(str(output_folder / (base_image_name+\"_anomaly.png\")))\n",
    "mask_image.save(str(output_folder / (base_image_name+\"_mask.png\")))\n",
    "back_image.save(str(output_folder / (back_image_name+\"_target.png\")))\n",
    "#Image.fromarray(result_image_mode).save()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.1.3 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"c:\\Users\\huang\\work\\dataset\\.venv\\Lib\\site-packages\\ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\huang\\work\\dataset\\.venv\\Lib\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\huang\\work\\dataset\\.venv\\Lib\\site-packages\\ipykernel\\kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\huang\\work\\dataset\\.venv\\Lib\\site-packages\\tornado\\platform\\asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Users\\huang\\.pyenv\\pyenv-win\\versions\\3.12.2\\Lib\\asyncio\\base_events.py\", line 639, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Users\\huang\\.pyenv\\pyenv-win\\versions\\3.12.2\\Lib\\asyncio\\base_events.py\", line 1985, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Users\\huang\\.pyenv\\pyenv-win\\versions\\3.12.2\\Lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\huang\\work\\dataset\\.venv\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\huang\\work\\dataset\\.venv\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\huang\\work\\dataset\\.venv\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\huang\\work\\dataset\\.venv\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"c:\\Users\\huang\\work\\dataset\\.venv\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\huang\\work\\dataset\\.venv\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\Users\\huang\\work\\dataset\\.venv\\Lib\\site-packages\\ipykernel\\zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\huang\\work\\dataset\\.venv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3075, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\Users\\huang\\work\\dataset\\.venv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3130, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"c:\\Users\\huang\\work\\dataset\\.venv\\Lib\\site-packages\\IPython\\core\\async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\huang\\work\\dataset\\.venv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3334, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\Users\\huang\\work\\dataset\\.venv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3517, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"c:\\Users\\huang\\work\\dataset\\.venv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3577, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\huang\\AppData\\Local\\Temp\\ipykernel_34040\\2292802235.py\", line 1, in <module>\n",
      "    import src.pic_process as pic_pro\n",
      "  File \"c:\\Users\\huang\\work\\dataset\\src\\pic_process.py\", line 4, in <module>\n",
      "    from torchvision import transforms\n",
      "  File \"c:\\Users\\huang\\work\\dataset\\.venv\\Lib\\site-packages\\torchvision\\__init__.py\", line 5, in <module>\n",
      "    import torch\n",
      "  File \"c:\\Users\\huang\\work\\dataset\\.venv\\Lib\\site-packages\\torch\\__init__.py\", line 1477, in <module>\n",
      "    from .functional import *  # noqa: F403\n",
      "  File \"c:\\Users\\huang\\work\\dataset\\.venv\\Lib\\site-packages\\torch\\functional.py\", line 9, in <module>\n",
      "    import torch.nn.functional as F\n",
      "  File \"c:\\Users\\huang\\work\\dataset\\.venv\\Lib\\site-packages\\torch\\nn\\__init__.py\", line 1, in <module>\n",
      "    from .modules import *  # noqa: F403\n",
      "  File \"c:\\Users\\huang\\work\\dataset\\.venv\\Lib\\site-packages\\torch\\nn\\modules\\__init__.py\", line 35, in <module>\n",
      "    from .transformer import TransformerEncoder, TransformerDecoder, \\\n",
      "  File \"c:\\Users\\huang\\work\\dataset\\.venv\\Lib\\site-packages\\torch\\nn\\modules\\transformer.py\", line 20, in <module>\n",
      "    device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),\n",
      "c:\\Users\\huang\\work\\dataset\\.venv\\Lib\\site-packages\\torch\\nn\\modules\\transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at ..\\torch\\csrc\\utils\\tensor_numpy.cpp:84.)\n",
      "  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Saved: C:\\Users\\huang\\work\\dataset\\calibration\\data\\20241209\\anomaly\\1_12_01_A1_0150_I.tif and C:\\Users\\huang\\work\\dataset\\calibration\\data\\20241209\\anomaly\\1_12_01_A1_0150_O.tif\n"
     ]
    }
   ],
   "source": [
    "import src.pic_process as pic_pro\n",
    "from pathlib import Path\n",
    "pic_pro.split_images_in_folder(Path(r\"C:\\Users\\huang\\work\\dataset\\calibration\\data\\20241209\\anomaly\"))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# genearate mask_image\n",
    "result_folder= Path(\"..\\\\data\\\\output\\\\20241118\\\\rd4ad_resnet18_512_cc_70epoch\\\\version_0\")\n",
    "anomaly_data = pd.read_csv(result_folder / '20241118anomalymaps.csv', header=None).values\n",
    "anomaly_scores = anomaly_data.reshape(18, 1, 512, 512)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
